### ISSUE TITLE
sRGB Values are Logarithmic

### ISSUE THREAD

**Issue by slime-horse** [mjswensen/color-steps#1]
sRGB values (255) are logarithmic not linear. Because of this 50% brightness between 0 and 255 is actually around 188. 

Take a look at this package I published It converts log sRGB to linear values.
https://www.npmjs.com/package/srgb-logarithmic-and-linear-colour-conversion

You can read more about it here http://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/

**Comment by mjswensen** [comment]
@grahm Thank you for the article and package! That was super helpful and informative—I had no idea that sRGB values were logarithmic.

I've started to implement the log to linear correction using your package, but I'm not sure if I'm doing something wrong. Say I'm trying to calculate 5 shades between white and black. I'm using this algorithm:

```
const delta = (colorTwoLinear - colorOneLinear) / (count + 1);
```

If I plug in `1` (`colorTwoLinear`), `0` (`colorOneLinear`), and `5` (`count`), I get `0.166666667` as my delta.

Then I calculate the first shade using this algorithm:

```
colorOneLinear + delta
```

Which of course gives me `0.166666667` again.

When I run that through `linToLog()` I get `113`. But `113` seems way too high to be the first shade above black. Here's my output:

![image](https://user-images.githubusercontent.com/1591879/34674725-3786b6b4-f444-11e7-96cb-5454c955ac56.png)

Can you spot anything I'm doing wrong? (See my [`log` branch](https://github.com/mjswensen/color-steps/tree/log) for reference.)

**Comment by slime-horse** [comment]
So after rereading the blog post it seems like when working with grayscale (in some use cases) it is actually best calculated in logarithmic sRGB because of perceptual linearity.

http://blog.johnnovak.net/2016/09/21/what-every-coder-should-know-about-gamma/ 

I create two tests in photoshop `white -> black` and `blue -> red`. In both of the following test the left colors are calculated in linear and on the right colors are calculated in logarithmic. 
They are also both 5 steps like your own example with a 6th step being the solid final color as a perceptual reference.

In your use case you should check for gray scale before converting to linear.
I'll do some more research on this and update my docs and this github issue on how to deal with grayscale, rgb -> grayscale, low saturation levels as those could possible also benefit perceptual linearity, and may be better suited to logarithmic sRGB conversions  

white -> black https://i.imgur.com/nStqeq2.png
blue -> red https://i.imgur.com/qscfU6o.png
